### ISSUE TITLE
how to display the power consumption data for the attack and reference scenarios represented on the same graph, including both the UDP server and client.

### ISSUE THREAD

**Issue by yahya-93** [crond-jaist/iotrain-lab#1]
i want to display the power consumption data for the attack and reference scenarios represented on the same graph, including both the UDP server and client.
like the graph showed in the step 7 on the tutorial
thank you

**Comment by crond-jaist** [comment]
Hi,
I think that you are referring to the Flooding Attack example. As mentioned in the tutorial, the `plot_oml_consum` script can be used to plot individual graphs, but as far as I remember for the summary graphs you mentioned we simply used Excel. You just need to extract and load the appropriate data from the `.oml` files created during the experiment.
Of course you could use other tools instead of Excel, such as Matlab, Octave, gnuplot and so on. I hope this helps.
Best wishes,
Razvan

**Comment by yahya-93** [comment]
Hello,
Thank you for your reply.
I wanted to know exactly how you put the data from the file ~/.iot-lab/last/consumption/m3-11.oml in the excel file to have this kind of graph. because the file ~/.iot-lab/last/consumption/m3-11.oml contains several columns which I can't put the difference between them.

**Comment by crond-jaist** [comment]
Hi,
I'm sorry but I didn't do this myself, so I cannot tell you exactly. I think you can put data from the OML file in different columns in Excel, then use the Excel plotting functionality to show them in one graph. Please try to search the Internet for how to use this feature of Excel. As I said, you can use any other plotting tool, like Matlab, Octave, or gnuplot, if you are not familiar with Excel.
Best wishes,
Razvan

**Comment by yahya-93** [comment]
Hello,
Thank you for your reply.
do you have an idea about the meaning of these columns in the .oml file 
https://github.com/crond-jaist/iotrain-lab/blob/master/database/fundamental_training/devices/consumption_monitoring/consumption_data.png

**Comment by crond-jaist** [comment]
Hi,
We are not the developers of FIT IoT-LAB, so for the format of the data files generated by their testbed you should check their documentation. 
For example, for consumption monitoring I found the following page:
https://iot-lab.github.io/docs/tools/consumption-monitoring/
There is also a page about radio monitoring:
https://iot-lab.github.io/docs/tools/radio-monitoring/
For the screenshot you mentioned, my understanding it that power is saved in the 3rd column counting from the right (for which the first value reads "0.147298"). The information in the header ("power:double") provides a hint about this.
Best wishes,
Razvan

**Comment by crond-jaist** [comment]
Closed since there was no follow-up for a couple of months.
